name: Build, Test, and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"

      - name: Install Python and MSVC via Chocolatey
        run: |
          choco install python -y
          choco install visualstudio2026buildtools --includeOptional -y

      - name: Instaall Docker Engine via Chocolatey
        run: |
          choco install docker-engine

      - name: Setup Git Bash
        run: |
          echo "C:\Program Files\Git\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: "c-cpp, javascript-typescript"
          queries: security-and-quality

      - name: Build with build.sh
        shell: sh
        run: export HOME=$(pwd) && sh ./build.sh

      - name: Perform CodeQL Static Analysis
        uses: github/codeql-action/analyze@v4
        with:
          upload: partial

      - name: Run unit tests
        shell: sh
        run: npm run test

      - name: Extract version from package.json
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && success()
        run: |
          echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Create Git tag
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && success()
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "v${{ env.PACKAGE_VERSION }}" -m "Release v${{ env.PACKAGE_VERSION }}"
          git push origin "v${{ env.PACKAGE_VERSION }}"

      - name: Publish to npm
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && success()
        run: npm publish
