name: Build, Test, and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Install Python and MSVC via Chocolatey
        run: |
          choco install python -y
          choco install visualstudio2026buildtools --includeOptional -y

      - name: Setup Git Bash
        run: |
          echo "C:\Program Files\Git\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build with build.sh
        shell: sh
        run: sh ./build.sh

      - name: Run unit tests
        run: npm run test

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: "cpp, javascript-typescript"
          queries: security-and-quality

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
        with:
          category: "/language:cpp"
          upload: partial

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
        with:
          category: "/language:javascript-typescript"
          upload: partial

    #   - name: Publish to npm
    #     if: github.event_name == 'push' && github.ref == 'refs/heads/main' && success()
    #     run: npm publish --dry-run
    #     env:
    #       NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
