name: Build, Test, and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"

      - name: Install Python and MSVC via Chocolatey
        run: |
          choco install python -y
          choco install visualstudio2026buildtools --includeOptional -y

      - name: Upgrade Docker via Chocolatey
        run: |
          choco upgrade docker-cli

      - name: Setup Git Bash
        run: |
          echo "C:\Program Files\Git\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: "c-cpp, javascript-typescript"
          queries: security-and-quality

      - name: Build with build.sh
        shell: sh
        run: export HOME=$(pwd) && sh ./build.sh

      - name: Perform CodeQL Analysis for C/C++
        uses: github/codeql-action/analyze@v4
        with:
          category: "/language:c-cpp"
          upload: partial

      - name: Perform CodeQL Analysis for JS/TS
        uses: github/codeql-action/analyze@v4
        with:
          category: "/language:javascript-typescript"
          upload: partial

      - name: Run unit tests
        uses: nick-fields/retry@v3
        with:
          max_attempts: 5
          timeout_minutes: 1
          command: npm run test

      - name: Publish to npm
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && success()
        run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
